#!/bin/bash

if [ -z "$1" ]
then
  DIR="./*.out"
else
  DIR="$1/*.out"
fi

export LD_LIBRARY_PATH="$(pwd):$LD_LIBRARY_PATH"

for f in $DIR
do
  if [[ $f != *.out ]]
  then
    continue
  fi

  valgrind -q --leak-check=full --malloc-fill=5d --free-fill=3e --error-exitcode=2 "$f"
  EXIT_CODE="$?"

  if [ "$EXIT_CODE" != "0" ]
  then
    echo -e "\n\e[1;31m(exit code $EXIT_CODE)\e[0m\n"
    exit $EXIT_CODE
  else
    time "$f" 1> /dev/null
  fi
done
